index:
	gcc heap.c conjuntos.c grafo.c busca.c kruskal.c prim.c djikstra.c main.c -c
	gcc heap.o conjuntos.o grafo.o busca.o kruskal.o prim.o djikstra.o main.o -o exec
clear:
	rm heap.o conjuntos.o grafo.o busca.o kruskal.o prim.o djikstra.o main.o
	rm exec
